"""
Validation script for all 14 H5 files generated by MATLAB conversion pipeline.
Checks structure, ETI, global quantities, tracks, and metadata.
"""

import h5py
from pathlib import Path
import json
import sys

# Import validation function from previous script
sys.path.insert(0, str(Path(__file__).parent.parent / '2025-11-11'))
from validate_h5_files import validate_h5_file

def main():
    """Validate all 14 H5 files."""
    h5_dir = Path(r"D:\INDYsim\data\h5_files")
    
    # Get all H5 files
    all_files = sorted(h5_dir.glob("*.h5"))
    
    if not all_files:
        print("ERROR: No H5 files found in data/h5_files/")
        return []
    
    print("=" * 80)
    print("H5 File Validation Report - All 14 Files")
    print("=" * 80)
    print(f"\nFound {len(all_files)} H5 files to validate\n")
    
    all_results = []
    
    # Group by ESET for spot-check reporting
    eset_groups = {
        'T_Re_Sq_0to250PWM_30#C_Bl_7PWM': [],
        'T_Re_Sq_0to250PWM_30#T_Bl_Sq_5to15PWM_30': [],
        'T_Re_Sq_50to250PWM_30#C_Bl_7PWM': [],
        'T_Re_Sq_50to250PWM_30#T_Bl_Sq_5to15PWM_30': []
    }
    
    for filepath in all_files:
        filename = filepath.name
        # Determine ESET from filename
        for eset_key in eset_groups.keys():
            if eset_key in filename:
                eset_groups[eset_key].append(filepath)
                break
    
    # Validate all files
    for filepath in all_files:
        print(f"\n{'='*80}")
        print(f"Validating: {filepath.name}")
        print(f"{'='*80}")
        
        result = validate_h5_file(filepath)
        all_results.append(result)
        
        # Print summary
        print(f"\nStatus: {result['status']}")
        
        if result.get('error'):
            print(f"ERROR: {result['error']}")
        
        if result.get('errors'):
            print(f"\nErrors ({len(result['errors'])}):")
            for err in result['errors']:
                print(f"  - {err}")
        
        if result.get('warnings'):
            print(f"\nWarnings ({len(result['warnings'])}):")
            for warn in result['warnings']:
                print(f"  - {warn}")
        
        # Print check details
        print(f"\nCheck Details:")
        for check_name, check_result in result.get('checks', {}).items():
            status = check_result.get('status', 'UNKNOWN')
            print(f"  {check_name}: {status}")
            if 'shape' in check_result:
                print(f"    Shape: {check_result['shape']}")
            if 'num_tracks' in check_result:
                print(f"    Tracks: {check_result['num_tracks']}")
            if 'size_mb' in check_result:
                print(f"    Size: {check_result['size_mb']} MB")
    
    # Summary
    print(f"\n{'='*80}")
    print("Summary")
    print(f"{'='*80}")
    
    passed = sum(1 for r in all_results if r['status'] == 'PASS')
    failed = sum(1 for r in all_results if r['status'] == 'FAIL')
    errors = sum(1 for r in all_results if r['status'] == 'ERROR')
    
    print(f"\nTotal files: {len(all_results)}")
    print(f"Passed: {passed}")
    print(f"Failed: {failed}")
    print(f"Errors: {errors}")
    
    # Spot-check summary by ESET
    print(f"\n{'='*80}")
    print("Spot-Check Summary by ESET")
    print(f"{'='*80}")
    
    for eset_name, files in eset_groups.items():
        print(f"\n{eset_name}: {len(files)} files")
        eset_results = [r for r in all_results if any(Path(r['file']).name == f.name for f in files)]
        eset_passed = sum(1 for r in eset_results if r['status'] == 'PASS')
        eset_failed = sum(1 for r in eset_results if r['status'] == 'FAIL')
        print(f"  Passed: {eset_passed}/{len(eset_results)}")
        print(f"  Failed: {eset_failed}/{len(eset_results)}")
        
        # Show first 2 files as spot-check
        spot_check = files[:2]
        print(f"  Spot-check files:")
        for f in spot_check:
            result = next((r for r in all_results if Path(r['file']).name == f.name), None)
            if result:
                status_icon = "✅" if result['status'] == 'PASS' else "❌"
                print(f"    {status_icon} {f.name} - {result['status']}")
    
    # Save detailed results to JSON
    output_file = Path(__file__).parent / 'h5_validation_results.json'
    with open(output_file, 'w') as f:
        json.dump(all_results, f, indent=2, default=str)
    
    print(f"\n{'='*80}")
    print(f"Detailed results saved to: {output_file}")
    print(f"{'='*80}")
    
    return all_results

if __name__ == '__main__':
    main()

