"""
Validation script for H5 files generated by MATLAB conversion pipeline.
Checks structure, ETI, global quantities, tracks, and metadata.
"""

import h5py
from pathlib import Path
import json

def validate_h5_file(filepath):
    """Validate a single H5 file against mechanobro's checklist."""
    filepath = Path(filepath)
    
    if not filepath.exists():
        return {
            'file': str(filepath),
            'status': 'ERROR',
            'error': 'File not found'
        }
    
    results = {
        'file': str(filepath),
        'status': 'PASS',
        'errors': [],
        'warnings': [],
        'checks': {}
    }
    
    try:
        with h5py.File(filepath, 'r') as f:
            # Check 1: ETI at root level
            if 'eti' in f:
                eti_shape = f['eti'].shape
                results['checks']['eti_at_root'] = {
                    'status': 'PASS',
                    'shape': eti_shape,
                    'dtype': str(f['eti'].dtype)
                }
            else:
                results['checks']['eti_at_root'] = {
                    'status': 'FAIL',
                    'error': 'ETI not found at root level'
                }
                results['errors'].append('ETI missing at root')
                results['status'] = 'FAIL'
            
            # Check 2: Root structure keys
            expected_keys = ['eti', 'experiment_info', 'global_quantities', 'led_data', 
                           'metadata', 'stimulus', 'tracks']
            actual_keys = sorted(list(f.keys()))
            missing_keys = [k for k in expected_keys if k not in actual_keys]
            extra_keys = [k for k in actual_keys if k not in expected_keys]
            
            results['checks']['root_structure'] = {
                'status': 'PASS' if not missing_keys else 'FAIL',
                'expected': expected_keys,
                'actual': actual_keys,
                'missing': missing_keys,
                'extra': extra_keys
            }
            
            if missing_keys:
                results['errors'].append(f'Missing root keys: {missing_keys}')
                results['status'] = 'FAIL'
            if extra_keys:
                results['warnings'].append(f'Extra root keys: {extra_keys}')
            
            # Check 3: Track structure
            if 'tracks' in f:
                track_keys = list(f['tracks'].keys())
                num_tracks = len(track_keys)
                
                if num_tracks > 0:
                    # Check first track structure
                    first_track = f['tracks'][track_keys[0]]
                    track_structure = {
                        'points': 'points' in first_track,
                        'derived_quantities': 'derived_quantities' in first_track,
                        'state': 'state' in first_track,
                        'metadata': 'metadata' in first_track
                    }
                    
                    missing_track_structure = [k for k, v in track_structure.items() if not v]
                    
                    results['checks']['track_structure'] = {
                        'status': 'PASS' if not missing_track_structure else 'FAIL',
                        'num_tracks': num_tracks,
                        'first_track_structure': track_structure,
                        'missing': missing_track_structure
                    }
                    
                    if missing_track_structure:
                        results['errors'].append(f'Missing track structure: {missing_track_structure}')
                        results['status'] = 'FAIL'
                else:
                    results['checks']['track_structure'] = {
                        'status': 'WARN',
                        'num_tracks': 0,
                        'warning': 'No tracks found'
                    }
                    results['warnings'].append('No tracks in file')
            else:
                results['checks']['track_structure'] = {
                    'status': 'FAIL',
                    'error': 'tracks group not found'
                }
                results['errors'].append('tracks group missing')
                results['status'] = 'FAIL'
            
            # Check 4: Global quantities (LED values)
            if 'global_quantities' in f:
                gq_keys = sorted(list(f['global_quantities'].keys()))
                expected_led = ['led1Val', 'led2Val']
                found_led = [k for k in expected_led if k in gq_keys]
                
                led_details = {}
                for led_key in found_led:
                    if 'yData' in f['global_quantities'][led_key]:
                        led_details[led_key] = {
                            'shape': f['global_quantities'][led_key]['yData'].shape,
                            'dtype': str(f['global_quantities'][led_key]['yData'].dtype)
                        }
                
                results['checks']['global_quantities'] = {
                    'status': 'PASS' if len(found_led) > 0 else 'WARN',
                    'all_keys': gq_keys,
                    'led_keys_found': found_led,
                    'led_details': led_details
                }
                
                if len(found_led) == 0:
                    results['warnings'].append('No LED values found in global_quantities')
            else:
                results['checks']['global_quantities'] = {
                    'status': 'FAIL',
                    'error': 'global_quantities group not found'
                }
                results['errors'].append('global_quantities group missing')
                results['status'] = 'FAIL'
            
            # Check 5: Metadata
            if 'metadata' in f:
                metadata_attrs = dict(f['metadata'].attrs)
                expected_attrs = ['has_eti', 'export_tier', 'num_tracks', 'num_frames']
                found_attrs = {k: metadata_attrs.get(k) for k in expected_attrs if k in metadata_attrs}
                missing_attrs = [k for k in expected_attrs if k not in metadata_attrs]
                
                results['checks']['metadata'] = {
                    'status': 'PASS' if not missing_attrs else 'WARN',
                    'all_attrs': metadata_attrs,
                    'found_attrs': found_attrs,
                    'missing_attrs': missing_attrs
                }
                
                if missing_attrs:
                    results['warnings'].append(f'Missing metadata attrs: {missing_attrs}')
                
                # Check critical metadata values
                if 'has_eti' in metadata_attrs:
                    if not metadata_attrs['has_eti']:
                        results['errors'].append('has_eti is False in metadata')
                        results['status'] = 'FAIL'
            else:
                results['checks']['metadata'] = {
                    'status': 'FAIL',
                    'error': 'metadata group not found'
                }
                results['errors'].append('metadata group missing')
                results['status'] = 'FAIL'
            
            # Check 6: File size
            file_size_mb = filepath.stat().st_size / (1024 * 1024)
            results['checks']['file_size'] = {
                'status': 'PASS',
                'size_mb': round(file_size_mb, 2),
                'expected_range': '100-300 MB'
            }
            
            if file_size_mb < 50:
                results['warnings'].append(f'File size ({file_size_mb:.2f} MB) seems small')
            elif file_size_mb > 500:
                results['warnings'].append(f'File size ({file_size_mb:.2f} MB) seems large')
            
            # Additional checks: Check ETI length matches metadata
            if 'eti' in f and 'metadata' in f:
                eti_length = f['eti'].shape[0]
                if 'num_frames' in f['metadata'].attrs:
                    num_frames = f['metadata'].attrs['num_frames']
                    if eti_length != num_frames:
                        results['warnings'].append(
                            f'ETI length ({eti_length}) does not match num_frames ({num_frames})'
                        )
            
            # Check LED value lengths vs ETI
            if 'global_quantities' in f and 'led1Val' in f['global_quantities']:
                if 'yData' in f['global_quantities']['led1Val']:
                    led_length = f['global_quantities']['led1Val']['yData'].shape[0]
                    if 'eti' in f:
                        eti_length = f['eti'].shape[0]
                        if led_length != eti_length:
                            results['checks']['led_eti_length_match'] = {
                                'status': 'WARN',
                                'led_length': led_length,
                                'eti_length': eti_length,
                                'difference': abs(led_length - eti_length)
                            }
                            results['warnings'].append(
                                f'LED length ({led_length}) differs from ETI length ({eti_length})'
                            )
                        else:
                            results['checks']['led_eti_length_match'] = {
                                'status': 'PASS',
                                'length': led_length
                            }
    
    except Exception as e:
        results['status'] = 'ERROR'
        results['error'] = str(e)
        results['checks'] = {}
    
    return results

def main():
    """Validate all test H5 files."""
    test_files = [
        r"D:\INDYsim\data\h5_files\GMR61@GMR61_T_Re_Sq_0to250PWM_30#C_Bl_7PWM_202510291713.h5",
        r"D:\INDYsim\data\h5_files\GMR61@GMR61_T_Re_Sq_0to250PWM_30#C_Bl_7PWM_202510301228.h5",
        r"D:\INDYsim\data\h5_files\GMR61@GMR61_T_Re_Sq_0to250PWM_30#C_Bl_7PWM_202510301408.h5"
    ]
    
    print("=" * 80)
    print("H5 File Validation Report")
    print("=" * 80)
    print()
    
    all_results = []
    
    for filepath in test_files:
        print(f"\n{'='*80}")
        print(f"Validating: {Path(filepath).name}")
        print(f"{'='*80}")
        
        result = validate_h5_file(filepath)
        all_results.append(result)
        
        # Print summary
        print(f"\nStatus: {result['status']}")
        
        if result.get('error'):
            print(f"ERROR: {result['error']}")
        
        if result.get('errors'):
            print(f"\nErrors ({len(result['errors'])}):")
            for err in result['errors']:
                print(f"  - {err}")
        
        if result.get('warnings'):
            print(f"\nWarnings ({len(result['warnings'])}):")
            for warn in result['warnings']:
                print(f"  - {warn}")
        
        # Print check details
        print(f"\nCheck Details:")
        for check_name, check_result in result.get('checks', {}).items():
            status = check_result.get('status', 'UNKNOWN')
            print(f"  {check_name}: {status}")
            if 'shape' in check_result:
                print(f"    Shape: {check_result['shape']}")
            if 'num_tracks' in check_result:
                print(f"    Tracks: {check_result['num_tracks']}")
            if 'size_mb' in check_result:
                print(f"    Size: {check_result['size_mb']} MB")
    
    # Summary
    print(f"\n{'='*80}")
    print("Summary")
    print(f"{'='*80}")
    
    passed = sum(1 for r in all_results if r['status'] == 'PASS')
    failed = sum(1 for r in all_results if r['status'] == 'FAIL')
    errors = sum(1 for r in all_results if r['status'] == 'ERROR')
    
    print(f"Total files: {len(all_results)}")
    print(f"Passed: {passed}")
    print(f"Failed: {failed}")
    print(f"Errors: {errors}")
    
    # Save detailed results to JSON
    output_file = Path(__file__).parent / 'h5_validation_results.json'
    with open(output_file, 'w') as f:
        json.dump(all_results, f, indent=2, default=str)
    
    print(f"\nDetailed results saved to: {output_file}")
    
    return all_results

if __name__ == '__main__':
    main()

